version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  react-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      - chat-service
    environment:
      - REACT_APP_BACKEND_PROTOCOL=change-me
      - REACT_APP_BACKEND_HOST=change-me.com
      - REACT_APP_BACKEND_PORT=change-me

  chat-service:
    build: 
      context: ./backend/chat-service
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8181:8181"
volumes:
  mongo-data: