version: '3.8'
services:
  mongo1:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo1:/data/db
    command: mongod --replSet rs0

  mongo2:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo2:/data/db
    command: mongod --replSet rs0

  mongo3:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27019:27017
    volumes:
      - mongo3:/data/db
    command: mongod --replSet rs0

  setup:
    image: mongo:4.4.6
    restart: on-failure
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      bash -c '
        sleep 10 &&
        mongo --host 192.168.1.8:27017 --eval "rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"192.168.1.8:27017\"}, {_id: 1, host: \"192.168.1.8:27018\"}, {_id: 2, host: \"192.168.1.8:27019\"}]});"
      '

volumes:
  mongo1:
  mongo2:
  mongo3:
