version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  react-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      - chat-service
    environment:
      - MONGO_URL=mongodb://mongo:27017

  chat-service:
    build: 
      context: ./backend/chat-service
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8181:8181"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017