version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  react-app:
    image: 'kingchan818/chatgpt-pro'
    ports:
      - '3222:3000'
    depends_on:
      - chat-service
    environment:
      - REACT_APP_BACKEND_PROTOCOL={{backend_protocol}}
      - REACT_APP_BACKEND_PATH={{backend_path}}
      - REACT_APP_BACKEND_HOST={{backend_host}}
      - REACT_APP_BACKEND_PORT={{backend_port}}

  chat-service:
    image: 'kingchan818/chatgpt-pro-chat-service'
    depends_on:
      - mongo
    ports:
      - '8181:8181'
volumes:
  mongo-data:
