version: '3.5'

services:
  chat-service:
    container_name: chat-service
    build:
      context: ./backend/chat-service
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend/chat-service:/app
      - /app/node_modules
    ports:
      - 8181:8181

  chatgpt:
    container_name: chatgpt
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./docker-env/frontend.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - chat-service
    restart: unless-stopped
