name: 'chatgpt-chat-service'

http:
  host: 'localhost'
  port: 8181
  cors:
    origin: '*' # or 'http://localhost:3000'

encryption:
  key: 'replace-me-with-aes-key'

mongodb:
  uris: 'mongodb://mongo:27017'
  database: 'chatgpt-pro'
  replicaSet: 'rs0'
  options:
    noDelay: true
    retryAttempts: 5
    directConnection: false

chatgpt:
  systemMessage: 'You are an AI that is playing the role of a 10 years experience software engineer.'
  debug: false
  systemMessageDelay: 1000
  timeoutMs: 160000
  completionParams:
    model: 'gpt-3.5-turbo-0613'
    temperature: 0.9

user:
  usageLimit: 5