name: Build and Push to Docker Hub

on:
  push:
    branches:
      - 'master'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image from Frontend Project
        uses: docker/build-push-action@v2
        with:
          context: .
          target: frontend-app
          push: true
          tags: kingchan818/chatgpt-pro:latest

  build-chat-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image from Frontend Project
        uses: docker/build-push-action@v2
        with:
          context: .
          target: backend-chat-service
          push: true
          tags: kingchan818/chatgpt-pro-chat-service:latest
