name: Build and Push to Docker Hub

on:
  push:
    branches:
      - 'master'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Copy pnpm-lock.yaml to chat-service directory
        run: cp pnpm-lock.yaml frontend/
      - name: Copy pnpm-workspace.yaml to chat-service directory
        run: cp pnpm-workspace.yaml frontend/
      - name: Build Docker image from Frontend Project
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: frontend/Dockerfile
          push: true
          tags: kingchan818/chatgpt-pro:latest
          target: final

  build-chat-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Copy pnpm-lock.yaml to chat-service directory
        run: cp pnpm-lock.yaml backend/chat-service/
      - name: Copy pnpm-workspace.yaml to chat-service directory
        run: cp pnpm-workspace.yaml backend/chat-service/
      - name: Build Docker image from Frontend Project
        uses: docker/build-push-action@v2
        with:
          context: ./backend/chat-service
          file: backend/chat-service/Dockerfile
          push: true
          tags: kingchan818/chatgpt-pro-chat-service:latest
          target: final
