name: Deploy

on:
  workflow_run:
    workflows: [Build and Push to Docker Hub]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Stack to Portainer
        uses: LGinC/portainer-stack-deploy@master
        with:
          serverurl: ${{ secrets.PORTAINER_HOST }}
          access_token: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          endpointId: 2
          variables: |
            backend_protocol=https
            backend_host=gptchatservice.calvinchan.space
            backend_port=443
          stackname: '${{ secrets.PORTAINER_STACK_NAME }}'
          docker_compose_path: 'docker-compose.yaml'