name: Unit test ocr service

on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setting up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
          run_install: false

      - name: Using Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installing Dependencies
        run: pnpm install

      - name: Run chat service test
        working-directory: ./backend/chat-service
        run: pnpm test

      - name: Run ocr service test
        working-directory: ./backend/ocr-service
        run: pnpm test
